plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  
collections:
  catalog:
    output: true

social:
  name: Модельер
  links:
    - https://www.facebook.com/model-r
    - https://www.instagram.com/model-r/

logo: /images/logo.jpg
url: https://model-r.ru

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.jpg
